---
- hosts: webserver
  vars:
  - docker_image: "{{docker_image}}"
  - version: "{{version}}"
  - aws_key: "{{aws_key}}"
  - aws_secret: "{{aws_secret}}"
  environment:
  - AWS_ACCESS_KEY_ID: "{{aws_key}}"
  - AWS_SECRET_ACCESS_KEY: "{{aws_secret}}"
  become: true
  tasks:
  - name: ECR docker login
    shell: "$(aws ecr get-login --no-include-email --region us-east-1)"

  - name: "Pulling {{version}} image"
    docker_image:
      pull: yes
      name: "{{docker_image}}"

    #name: Kill previous container if any
  - docker_container:
      name: "{{version}}"
      state: absent
      force_kill: yes

  - name: Launch container with new image
    docker_container:
      recreate: yes
      name: "{{version}}"
      image: "{{docker_image}}"
      restart_policy: on-failure
      state: started
      exposed_ports:
      - 8000
